audio_root_train: "datasets/VGGSound/train/wavs"
vision_root_train: "datasets/VGGSound/train/images"
train_index: "vggsound_10k.json"
audio_root_val: "VGGSound/test/wavs"
vision_root_val: "VGGSound/test/images"
box_json: "vggss_test.json"

ckpt: "."
work_dir: "temp"
num_epochs: 100
seed: 1234
logging_iters: 100
batch_size: 128
workers: 8